import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ClientOnlyWrapper from "@/utils/ClientOnlyWrapper";
import { ToastContainer } from "react-toastify";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className + "min-h-[100vh]"}>
        <NextIntlClientProvider messages={messages}>
          <ToastContainer />
          <ClientOnlyWrapper>
            <Header></Header>
            {children}
          </ClientOnlyWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
