import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ClientOnlyWrapper from "@/components/ClientOnlyWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <ClientOnlyWrapper>
          <Header>{children}</Header>
        </ClientOnlyWrapper>
      </body>
    </html>
  );
}
